### ISSUE TITLE
Error in Account-Creator: Max retries exceeded

### ISSUE THREAD

**Issue by helenclarko** [Merubokkusu/discord-spam-bots#44]
Below is my error log, I really hope you can help.

OS: Windows
Python Version: 3.6.4
Requirements installed

```
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000024A342B2390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: http://2captcha.com/in.php?key=THISISMYAPIKEY&method=userrecaptcha&googlekey=6Lef5iQTAAAAAKeIvIY-DeexoO3gj7ryl9rLMEnn&pageurl=https://discordapp.com/api/v6/auth/register (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A342B2390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 65, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 34, in create
    captcha_id = s.post("http://2captcha.com/in.php?key={}&method=userrecaptcha&googlekey={}&pageurl={}".format(API_KEY, site_key, url), proxies=proxy).text.split('|')[1]
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: http://2captcha.com/in.php?key=THISISMYAPIKEY&method=userrecaptcha&googlekey=6Lef5iQTAAAAAKeIvIY-DeexoO3gj7ryl9rLMEnn&pageurl=https://discordapp.com/api/v6/auth/register (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A342B2390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
```

**Comment by Merubokkusu** [comment]
You're not using any proxies or atleast thats what its showing in this log
`requests.exceptions.ProxyError: HTTPConnectionPool(host='localhost', port=80): Max retries
`

**Comment by helenclarko** [comment]
Okay right, I was not sure if it was a requirement.

I now need to know what format it needs to be in.

the new error is:
```
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 65, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 34, in create
    captcha_id = s.post("http://2captcha.com/in.php?key={}&method=userrecaptcha&googlekey={}&pageurl={}".format(API_KEY, site_key, url), proxies=proxy).text.split('|')[1]
IndexError: list index out of range
```

And here is how my proxy list is formatted:

```
103.94.121.27
51.38.71.101
91.142.174.224
202.142.153.181
200.41.94.105
185.189.199.75
110.5.100.130
177.128.42.25
195.191.250.38
89.40.48.186
103.76.20.155
93.185.96.61
117.206.83.198
178.215.76.193
131.161.68.37
91.210.47.93
182.253.115.90
91.90.188.241
212.2.204.181
212.56.203.114
```

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/commit/fba443fa9c0e3e68ad3a9902f95492da86bfe147 Try this

**Comment by helenclarko** [comment]
Okay, progress:

I put that code change in 2 places:

```
    s = requests.Session()
    captcha_id = s.post("http://2captcha.com/in.php?key={}&method=userrecaptcha&googlekey={}&pageurl={}".format(API_KEY, site_key, url), proxies=proxy).text
    if '|' in captcha_id:
        captcha_id = captcha_id.split('|')[1]
    recaptcha_answer = s.get("http://2captcha.com/res.php?key={}&action=get&id={}".format(API_KEY, captcha_id), proxies=proxy).text
    print("solving ref captcha...")
    while 'CAPCHA_NOT_READY' in recaptcha_answer:
        sleep(5)
        recaptcha_answer = s.get("http://2captcha.com/res.php?key={}&action=get&id={}".format(API_KEY, captcha_id), proxies=proxy).text
    if '|' in recaptcha_answer:
        recaptcha_answer = recaptcha_answer.split('|')[1]
```
And I have this output:
```
solving ref captcha...
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 69, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 64, in create
    t = json.load(r.content)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
```

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/blob/master/bots/misc/account-creator/account_creator.py

Redownload and replace, test it now and let me know.

**Comment by helenclarko** [comment]
Ah, this seems to be getting me a step closer.

The error I get now is a Cannot connect to proxy error. I suspect this is an error with my proxy list.

I have a few questions about that.

Should my list be made up with IP addresses that by default are on port 80?
Should they accept https?

**Comment by Merubokkusu** [comment]
You can specify port by ip:port
I think I made a mistake with the https.

`    proxy = {
    'http': 'http://'+PROXY
    }`

Replace line 28-31

**Comment by helenclarko** [comment]
It sat there for a lot longer this time, then gave this error:

```
solving ref captcha...
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 64, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 60, in create
    t = json.load(r.content)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'bytes' object has no attribute 'read'
```

EDIT: Nevermind, seem to have fixed this by using the following on line 60:

```
        t = json.loads(r.content)
```

**Comment by helenclarko** [comment]
Almost there I think, just unable to write the token:

```
solving ref captcha...
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 64, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 62, in create
    file.writelines(t['token'] + '\n')
KeyError: 'token'
```

**Comment by Merubokkusu** [comment]
Sorry for the late response, I’ll have to purchase 2 captcha again to figure that one out.

**Comment by helenclarko** [comment]
THANKS DUDE!

Let me know if there is anything else I can help you with.

**Comment by helenclarko** [comment]
Is there any way I can share mine with you??

**Comment by Merubokkusu** [comment]
Fixed and tested.
![https://i.imgur.com/Ov5REuH.png](https://i.imgur.com/Ov5REuH.png)

Check just to make sure :)

**Comment by helenclarko** [comment]
Hmmm, I've no idea now.

I just grabbed the latest version and have the same problem:

```
solving captcha...
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 66, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 64, in create
    file.writelines(r.json()['token'] + '\n')
KeyError: 'token'
```
I dunnno if I'm just choosing bad proxies or if I'm being blocked out from Captcha.

**Comment by Merubokkusu** [comment]
Most likely bad proxies

**Comment by helenclarko** [comment]
Still no luck.

I'm just using https://free-proxy-list.net, is that a bad idea?

**Comment by Merubokkusu** [comment]
Generally free proxies are bad.
I think I used GatherProxy for testing.
There's also uProxy and Kidux (free)
